### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by peda** [KosyanMedia/tp-datepicker#5]
Hello,

I was wondering under which license you are distributing this datepicker? It looks really great :-)

I'd love to use it for one of my projects but I need to have the license question answered. 

Thanks in advance,
Peter

**Comment by pavel-gorlov** [comment]
Hi! MIT
https://github.com/KosyanMedia/tp-datepicker/commit/23fe487823b4f9a440137b926187df145dc9e462
Thank you!

**Comment by peda** [comment]
thanks
